import { jsPDF } from 'jspdf'

export type Invoice = {
  id: string
  client_name: string
  client_email: string
  amount: number
  status: string
  created_at: string
}

export async function generateInvoicePdf(invoice: Invoice): Promise<Blob> {
  const doc = new jsPDF()

  doc.setFontSize(18)
  doc.text('Invoice', 105, 20, { align: 'center' })

  doc.setFontSize(12)
  doc.text(`Invoice ID: ${invoice.id}`, 20, 40)
  doc.text(`Client Name: ${invoice.client_name}`, 20, 50)
  doc.text(`Client Email: ${invoice.client_email}`, 20, 60)
  doc.text(`Amount: R${invoice.amount.toFixed(2)}`, 20, 70)
  doc.text(`Status: ${invoice.status}`, 20, 80)
  doc.text(`Created At: ${new Date(invoice.created_at).toLocaleDateString()}`, 20, 90)

  // Optional footer or notes
  doc.setFontSize(10)
  doc.text('Generated by Neo Invoice', 105, 290, { align: 'center' })

  // ✅ Return as Blob for client-side download/view
  const pdfBlob = doc.output('blob')

  return pdfBlob
}
